### ISSUE TITLE
LA100.IEA_downscale_ctry

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#382] opened 2017-05-09 21:01 UTC
Repo needs to become private when this is started--will require commit of proprietary `en_nonOECD.csv` and `en_OECD.csv` files.

...or, use of the OPTIONAL_FILE mechanism.

**Comment by rplzzz** [comment] 2017-05-10 13:10
I'm not crazy about the idea of committing proprietary data to this repository.  A better strategy would be to use the optional file mechanism and to get the include the IEA files as a submodule (there is a repository on our internal BitBucket server that contains them).  If you don't have access to the internal server, you won't be able to update the submodule; therefore, the files won't be there, and the optional file mechanism will take over from there.

**Comment by bpbond** [comment] 2017-05-10 13:16
That's fine. Opened this issue b/c I didn't want to start someone on this without thinking about it, then have them commit the proprietary data open to the world.

**Comment by rplzzz** [comment] 2017-05-10 13:54
Perhaps we should add a pre-receive hook to reject any such attempt.

**Comment by bpbond** [comment] 2017-05-10 13:57
More trouble than it's worth IMO. This is the only chunk that uses those data; no one will start this chunk until they have the skeleton from me; so I think it'll be OK, barring a malicious proprietary-data-committer.

**Comment by bpbond** [comment] 2017-05-10 13:57
...that said, no harm in putting it in. The two files are listed above.

**Comment by rplzzz** [comment] 2017-05-10 14:02
Unfortunately, GitHub doesn't support pre-receive hooks, so the question is moot.

**Comment by bpbond** [comment] 2017-05-10 15:14
Basically, it looks like this chunk will take three optional inputs: the two listed above, as well as `L100.IEA_en_bal_ctry_hist.csv`. It will:

* If the proprietary data files are available, calculate `L100.IEA_en_bal_ctry_hist` (replicating existing data system logic) and return that to the driver
* If proprietary files are not available, instead return read-in `L100.IEA_en_bal_ctry_hist.csv`, i.e. pre-processed data that is committed into `inst/extdata/energy/`
* Otherwise, error.

**Comment by bpbond** [comment] 2017-05-17 16:24
Hey @pkyle whenever convenient - can you provide any metadata information (source, units, comments) you know re these files? Thanks.

* `en_nonOECD.csv` and `en_OECD.csv`
* `IEA_product_downscaling.csv`
* `IEA_ctry.csv`

**Comment by pkyle** [comment] 2017-05-17 18:36
**en_nonOECD.csv**
Title: Energy Balances of non-OECD Countries 1971-2010 (2012 Edition)
Source: International Energy Agency, https://www.iea.org/statistics/relateddatabases/energybalancesofnon-oecdcountries/
Units: kilotonnes of oil equivalent (ktoe), TJ (for heat flows), GWh (for electricity flows)
Description: Extended energy balances of non-OECD nations, exported from Beyond2020 Browser. Note that PRODUCT generally refers to fuel type, and FLOW generally refers to sector or process.

**en_OECD.csv**
Title: Energy Balances of OECD Countries 1960-2010 (2012 Edition)
Source: International Energy Agency, https://www.iea.org/statistics/relateddatabases/energybalancesofoecdcountries/
Units: kilotonnes of oil equivalent (ktoe), TJ (for heat flows), GWh (for electricity flows)
Description: Extended energy balances of OECD nations, exported from Beyond2020 Browser. Note that PRODUCT generally refers to fuel type, and FLOW generally refers to sector or process.

**IEA_product_downscaling**
Title: FLOW assigned to each PRODUCT for downscaling from composite countries to specific constituent countries.
Source: NA
Units: NA
Description: This mapping table assigns a FLOW (i.e., sector or process) to each PRODUCT (fuel) to be used for downscaling from composite countries like the USSR to the 15 countries, in years when only values for the composite nation are reported. This assignment is designed to address the very large discrepancies in sectoral attribution of fuels that occurred over the time series.

**IEA_ctry**
Title: Mapping from IEA countries or composite regions to country ISO codes.
Source: NA
Units: NA
Description: IEA_ctry refers to the name of the country or country group in the IEA Energy Balances. IEA_Fert_reg corresponds to the world region for which ammonia production volumes and energy intensities are reported in Table 4.15 of IEA (2007); Tracking Industrial Energy Efficiency and CO2 Emissions, https://www.iea.org/publications/freepublications/publication/tracking_emissions.pdf

**Comment by bpbond** [comment] 2017-05-18 00:37
You rock @pkyle - thanks.  👍

**Comment by bpbond** [comment] 2017-05-21 17:34
@pkyle I'm not sure I understand lines 115-118 of this chunk:
```R
L100.USSR_Yug_ctry_FLOW_PRODUCT <- subset( L100.USSR_Yug_ctry, paste( PRODUCT, FLOW ) %in% paste( IEA_product_downscaling$PRODUCT, IEA_product_downscaling$FLOW ) )
L100.USSR_Yug_FLOW_PRODUCT <- aggregate( L100.USSR_Yug_ctry_FLOW_PRODUCT[ "X1990" ],
      by=as.list( L100.USSR_Yug_ctry_FLOW_PRODUCT[ c( "IEAcomposite", "FLOW", "PRODUCT" ) ] ), sum )
L100.USSR_Yug_ctry_FLOW_PRODUCT$X1990_share <- L100.USSR_Yug_ctry_FLOW_PRODUCT$X1990 /
       L100.USSR_Yug_FLOW_PRODUCT$X1990[
          match( paste( L100.USSR_Yug_ctry_FLOW_PRODUCT$IEAcomposite, L100.USSR_Yug_ctry_FLOW_PRODUCT$PRODUCT ),
                 paste( L100.USSR_Yug_FLOW_PRODUCT$IEAcomposite, L100.USSR_Yug_FLOW_PRODUCT$PRODUCT ) ) ]
```

The first two steps (`subset` and `aggregate`) are straightforward. I'm confused, though, why the third step computing `1990_share` is matching by `IEA_composite` and `PRODUCT` but not `FLOW`, which is also a column in  `L100.USSR_Yug_FLOW_PRODUCT`. If we're not going to match by it, why aggregate by it in the previous step? Or is this a mistake, and should that third step be looking up the `1990_share` value by `IEA_composite`, `PRODUCT` **AND** `FLOW`?

Thanks!

**Comment by pkyle** [comment] 2017-05-22 03:23
Yeah, no doubt it's confusing, but I think it is implemented as intended! The basic problem here is that for the USSR and Yugoslavia, for most years between 1971 and 1989, the IEA didn't have much info on the sectoral allocation of fuel consumption, and a lot of the energy consumption is assigned to flows like ONONSPEC (other non-specified) and INONSPEC (industry non-specified). In other words the definition of the flows changes over the course of the time series.
This method is computing each (modern) nation's share of the total consumption of each product (i.e., fuel) in 1990 within the composite nation (i.e., USSR and Yugoslavia). The appropriate total for each product/fuel is set in the IEA_product_downscaling mapping file; the complication here is that the flow corresponding to total consumption differs by fuel. Total consumption of most fuels is indicated by the TPES (total primary energy supply) flow, but the TPES of secondary fuels (e.g., electricity, heat) is typically zero because these aren't primary energy, so other flows like TFC (total final consumption) are used.

**Closed** 2017-06-15 16:50 UTC
Labels: energy
